### PR TITLE
Rebuild: parallelize dependencies downloads

### PR DESCRIPTION
**Pull request by petrkotek**
This PR makes download of dependencies **parallel** when using `gvt rebuild` (i.e. addresses https://github.com/FiloSottile/gvt/issues/7) and significantly improves speed of the rebuild.

By default, 8 connections are used, however it's possible to override it using:
`gvt rebuild --connections X`.

This significantly improved speed of our travis builds (`gvt rebuild` was originally taking `115s`, now it's `21s` with 8 parallel download connections, i.e. more than 5x faster).

Use `?w=1` to review.

Please let me know, what do you think about it. Thanks!

### CODE REVIEW

**Comment by petrkotek** [comment]
I did some more testing of speed - results below
- Connections = count of concurrent connections
- Time = time spent with `gvt rebuild`

| Connections | Time |
| --- | --- |
| 1 | 10m 54s |
| 2 | 6m 3s |
| 4 | 3m 38s |
| 8 | 1m 59s |
| 16 | 1m 18s |
| 32 | 1m 8s |

Note: there was 53 dependencies.

**Comment by petrkotek** [comment]
ping @FiloSottile - i was wondering what's your opinion about this PR?

**Comment by FiloSottile** [comment]
Thanks @petrkotek! Looks good

**Comment by petrkotek** [comment]
Thank you, @FiloSottile :bow:

**Pull request merged**
